#Basic java stuff
language: java
jdk:
  - openjdk8

#Install tasks (Can't use apt - outdated)
install:
  - curl -s get.sdkman.io | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install gradle 5.5

#Our projects don't have a gradle wrapper
script: gradle build -Prelease

#Don't build untagged branches
branches:
  except:
    - untagged*

#Don't pester me about this stuff
notifications:
  email: false

#Deployment
deploy:
  provider: releases

  #Cleanup deletes the file we build
  skip_cleanup: true

  #Point to the "libs" folder
  file_glob: true
  file: build/libs/*

  #Acceptable repository
  on:
    repo: HelloWorldMinecraft/AutomaticInventory

  #API Key
  api_key:
    secure: Y+BVPRg1uI5QR9oUWzZZe+mCn9HX+w3tg3aqCHVd9WIJXZSAvdpkBc5GAuMT+AosZpyJbVbpATzY+qslpU2W91UiNaU6RfkLlWz3tjCPRIivjsTQX1Eknx6zZQKpm/LzudBPWzaYIbYK556R+kdqwHQVJDiXpNVlSQwuq+0J082k5iKtY4hQP1e9iG/l450AY5CgpjxLRdvjDQqS6S44cuPzdUPYgt+VYCp6lHcdRqvm7kGBejGtktyNuS4bY0A/1H1mkehMW9uOjfW9bUbZgAAbtVY6rmu6Fa7b4omQy0zrWJFelkUGw+mly+H73AmIho2QxzW1U+D29nOZUwe8+QuTlAWuR/POUuPNE95w1CxQaSaouzd8AiV8IppQfBDcmxAE8qVBQQln8COPiyQv6cre44O/P7uVia82Q2zw+pJffIu5YtFwB1X0ciH4aAbBBfFaHG6C27wx3tdxhGa3vYLiYcmIQNZmGRBd/J9jg9RFA9cg6GdGINK2x9r/xiLU5Zk2+msaIzH6aicO+65WpyU0W3aOxIyEHrlf2HouW4RXoGMrED/6D7OmucLw3CRl2gr9mevAHpRL+3Rod79n9FaInAoWGgF5/dDzipRQe5okYmHafuK31l3OYaRJIlSqpkyv5LInz67lyaZal6cK2YYy1KhVO8nknqhlC/MKrXA=
